Style file
SelmaNdapanda/Selma-Portfolio pull request #1
Opened 2022-07-01 19:11 UTC by SelmaNdapanda

In this file, I created CSS files for: Toolbar section and Headline Section

2022-07-01 20:05 UTC, gtekle requested changes
Hi @SelmaNdapanda :wave: , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![dog-pug](https://user-images.githubusercontent.com/44057863/176961748-d5319ad2-b9dc-4965-87a0-d34dcd9e338c.gif)



## Highlights
:heavy_check_mark: Linters setup correctly
:heavy_check_mark: Professional ReadMe

## Required Changes ♻️
_Check the comments under the review._

- [x] You should use a descriptive pull request title. A descriptive title briefly captures the changes included in the pull request. For example, `Portfolio: setup and mobile version skeleton` can be a good candidate pull request title.
![image](https://user-images.githubusercontent.com/44057863/176961704-2fa5b409-7f37-40cf-b26e-ef14a7982b6d.png)

- [x] You should make commits more frequently to capture the stages of changes while developing the milestone and use meaningful commit messages.
![image](https://user-images.githubusercontent.com/44057863/176961653-3a292a06-b313-498a-bebc-e5f3f911cc85.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 10:52 UTC, SelmaNdapanda commented on index.html
> +  </div>
Hi Sir. I am actually waiting for the second review.

2022-07-02 11:29 UTC, zhadier requested changes
# Hi @SelmaNdapanda  👋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🌤️ 

<img src="https://media4.giphy.com/media/5wWf7GR2nhgamhRnEuA/giphy.gif"/>

 ## Highlights

✔️ No linter errors
✔️ Github flow was setup correctly
✔️ Professional pull request title and description

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question @zhadier so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 11:29 UTC, zhadier commented on index.html
> +</nav>
- [ ] As the previous reviewer requested, kindly remove the borders around the logo and the header. As you can see below, the borders are still there
![image](https://user-images.githubusercontent.com/90556221/176998596-859f4b7a-6283-42bd-ada6-eb6705ee2317.png)
- [ ]   As the previous reviewer requested, kindly wrap the entire toolbar in a `header` tag instead of a `nav` since it is semantically a header at the top of your page. On the other hand, you should wrap the hamburger menu in a `nav` tag since it's purpose is to navigate around the page.

2022-07-02 11:29 UTC, zhadier commented on index.html
> +<section class="headline">
- [ ] As the previous reviewer requested, kindly alter the font size of the heading to match the Figma design, right now the heading is still too big as you can see below
![image](https://user-images.githubusercontent.com/90556221/176998714-b36b7a9a-1362-431c-b622-272d8795f118.png)

2022-07-02 11:29 UTC, zhadier commented on index.html
> +  </div>
- [ ] As the previous reviewer emphasized,  you can do away with most `div` wrappers since `h1` in itself can be styled by adding a class. Having too many `div`'s clutters the DOM.

2022-07-02 14:47 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @SelmaNdapanda        , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

[OPTIONAL] Kindly add a screenshot to your README file showing your webpage user Interface. You can use extentions like fireshot to capturer the entire page.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 15:15 UTC, merged